name: my-docker-project

services:
  # app:
  #   image: docker-image
  #   container_name: docker-image-container
  #   ports:
  #     - "8001:8000"
  #   volumes:
  #     - .:/app

  postgres:
    image: postgres
    container_name: docker-postgres-container
    ports:
      - "5432:5432"

    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    
    restart: unless-stopped
    

    volumes:
      - postgres_data:/var/lib/postgres/data

volumes:
  postgres_data:
    

